<?php

    use Magento\Framework\App\Config\ScopeConfigInterface;

    function getObjectManager()
    {
        return \Magento\Framework\App\ObjectManager::getInstance();
    }

    $objectManager = getObjectManager();

    // Get the store manager
    $storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
    $scopeConfig = $objectManager->get(ScopeConfigInterface::class);

    $code = 'razorpay';
    $magicActiveField = 'activate_magic';
    $buynowActiveField = 'activate_magic_buy_now';
    $keyField = 'key_id';

    $isMagicEnabled = $scopeConfig->getValue('payment/' . $code . '/' . $magicActiveField, \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
    $isBuynowEnabled = $scopeConfig->getValue('payment/' . $code . '/' . $buynowActiveField, \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
    $rzpKey = $scopeConfig->getValue('payment/' . $code . '/' . $keyField, \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

?>
<?php if ($isMagicEnabled == 1 && $isBuynowEnabled == 1) :?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Razorpay_Magento/js/magic-buy-now": {
                "submitUrl": "<?php echo $block->getUrl('razorpay/oneclick/placeorder') ?>",
                "sku": "<?php echo $block->getProduct()->getSku(); ?>",
                "callbackURL": "<?php echo $block->getUrl('razorpay/oneclick/completeorder') ?>",
                "key": "<?php echo $rzpKey ?>"
            }
        }
    }
</script>

<!-- <script type="text/javascript">
    var Razorpay = {
      "config": {
        "api": "https://api-web-magentobase.ext.dev.razorpay.in/",
       "frame": "https://api-web-magentobase.ext.dev.razorpay.in/test/checkout.html?branch=master",
      },
    }; 

     var rzpApi = Razorpay.config.api + 'v1/';
</script> -->

<script id="occ-template" type="text/x-occ-template">
    <button type="button" title="<?php echo __('Buy Now') ?>" class="action primary occ" id="product-oneclick-button">
        <span><?php echo __('Buy Now') ?></span>
    </button>
</script>

<script type="text/javascript"
    src="https://checkout.razorpay.com/v1/magic-checkout.js">
</script>

<?php endif; ?>

