<?php
/** @var \Magento\Catalog\Block\Product\View $block */
?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Razorpay_Magento/js/buy-now": {
                "isAvailableUrl": "<?php echo $block->getUrl('rest/V1/buttons/buynow/canshow/') ?>",
                "submitUrl": "<?php echo $block->getUrl('razorpay/oneclick/placeorder') ?>",
                "sku": "<?php echo $block->getProduct()->getSku(); ?>",
                "callbackURL": "<?php echo $block->getUrl('razorpay/oneclick/completeorder') ?>"
            }
        }
    }
</script>

<script type="text/javascript">
    var Razorpay = {
      "config": {
        "api": "https://api-web-magemo.ext.dev.razorpay.in/",
       "frame": "https://api-web-magemo.ext.dev.razorpay.in/test/checkout.html?branch=master",
      },
    }; 

     var rzpApi = Razorpay.config.api + 'v1/';
</script>

<script id="occ-template" type="text/x-occ-template">
    <button type="button" title="<?php echo __('One Click Checkout') ?>" class="action primary tocart occ" id="product-oneclick-button">
        <span><?php echo __('One Click Checkout') ?></span>
    </button>
</script>

<script type="text/javascript"
    src="https://checkout.razorpay.com/v1/magic-checkout.js">
</script>
