<script type="text/javascript">
    var razorpayOptions = <?php echo json_encode($this->fields());?>;
    var razorpayUtils = new RazorpayUtils(razorpayOptions);

    var onSuccess = function(data) {
        document.querySelector('#razorpay_payment_id').value = data.razorpay_payment_id;
        document.querySelector('#razorpay_order_id').value = data.razorpay_order_id;
        document.querySelector('#razorpay_signature').value = data.razorpay_signature;

        document.querySelector('form#razorpay').submit();
    };

    var onDismiss = function() {
        document.querySelector('form#razorpay').submit();
    };

    if (razorpayOptions.hasOwnProperty('error') === false && razorpayOptions.error !== false)
    {
        razorpayUtils.placeOrder(onSuccess, onDismiss);
    }
    else
    {
        window.location = "<?php echo $this->getFailureUrl(); ?>";
    }
</script>

<form name="razorpay" id="razorpay" method="post" action="<?php echo $this->getSuccessUrl(); ?>">
    <input id="razorpay_payment_id" name="razorpay_payment_id" type="hidden" value=""/>
    <input id="razorpay_order_id"   name="razorpay_order_id"   type="hidden" value=""/>
    <input id="razorpay_signature"  name="razorpay_signature"  type="hidden" value=""/>
    <input id="magento_order_id"    name="magento_order_id"    type="hidden" value="<?php echo $this->getMagentoOrderId(); ?>"/>
</form>

<h1>Please wait...</h1>
<p>Do not refresh the page or press back button</p>
