<?php $_code=$this->getMethodCode();?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
    var checkoutPayments = $('checkout-payment-method-load');

    checkoutPayments.on(
        'change',
        function(e)
        {
            var pMethodRazorpay = $('p_method_razorpay');

            var ddMethodRazorpay = $('dd_method_razorpay');

            var img;

            if (pMethodRazorpay.checked)
            {
                if (ddMethodRazorpay.getElementsByTagName('img').length === 0)
                {
                    img = document.createElement('IMG');
                    // TODO: Find a website where we can upload this
                    img.src = "https://goo.gl/emCStU";
                    ddMethodRazorpay.appendChild(img);
                }
            }
            else
            {
                // We are removing img child node when button is not checked
                img = ddMethodRazorpay.childNodes[1];

                ddMethodRazorpay.removeChild(img);
            }
        });
</script>