<?php
/** @var $block \Magento\Checkout\Block\Onepage\Link */
?>
<?php if ($block->isPossibleOnepageCheckout()) :?>
<button name="btnname" id="trybtn">Try it</button>

    <script>
        require(['jquery', 'myscript'], function($, myscript) {
            myscript();
        });
    </script>

<?php endif; ?>

    <!-- <script src="<?php //echo $block->getViewFileUrl('Razorpay_Magento::js/view/payment/razorpay-payments.js')?>"></script> -->
<!-- {
                "Magento_Checkout/js/proceed-to-checkout":{
                    "checkoutUrl":"Razorpay_Magento::js/view/payment/razorpay-payments.js"
                }
            } -->